export const usageDate: Array<string> = [
  "Luhya",
  "Turkmen",
  "Scottish",
  "Yolngu",
  "Theatre",
  "Ancient Aramaic",
  "Ancient Berber",
  "Dari Persian",
  "Javanese",
  "Old Norman",
  "Jewish",
  "Sanskrit",
  "Mbundu",
  "Sundanese",
  "Tumbuka",
  "Tuareg",
  "Flemish",
  "Cree",
  "French",
  "Greek",
  "Spanish",
  "Armenian Mythology",
  "Punjabi",
  "Polynesian Mythology",
  "Georgian",
  "Thai",
  "Kongo",
  "Ossetian",
  "Ganda",
  "Caucasian Mythology",
  "Sorbian",
  "Welsh",
  "Hinduism",
  "Biblical Italian",
  "Choctaw",
  "Mongolian",
  "Bulgarian",
  "Turkic Mythology",
  "Norman",
  "Japanese Mythology",
  "Biblical Greek",
  "Balinese",
  "Anglo-Saxon Mythology",
  "Anglo-Saxon",
  "Slovak",
  "Ewe",
  "Middle Persian",
  "Navajo",
  "Urhobo",
  "Comorian",
  "Serbian",
  "Tagalog",
  "Kiga",
  "Greenlandic",
  "Biblical Hebrew",
  "Medieval Scandinavian",
  "Italian",
  "Zulu",
  "Indigenous American",
  "Tupi",
  "Lao",
  "Chinese Mythology",
  "Medieval Scottish",
  "Filipino",
  "Theology",
  "Ancient Greek",
  "Mohawk",
  "American",
  "Walloon",
  "Tooro",
  "Vietnamese",
  "Old Persian",
  "Assamese",
  "Oromo",
  "Tswana",
  "Biblical Finnish",
  "Sami",
  "Pashto",
  "Icelandic",
  "Oneida",
  "Occitan",
  "Korean",
  "Bashkir",
  "Cheyenne",
  "Kazakh",
  "Catalan",
  "Estonian",
  "Frankish",
  "Biblical Latin",
  "Igbo Mythology",
  "Hausa",
  "Old Welsh",
  "Medieval German",
  "Powhatan",
  "Hmong",
  "Gaulish",
  "Medieval Occitan",
  "Aztec and Toltec Mythology",
  "Russian",
  "Dargin",
  "Medieval English",
  "Bengali",
  "Afro-American Mythology",
  "Sotho",
  "Albanian",
  "Sioux",
  "Luo",
  "Medieval Spanish",
  "Avestan",
  "Low German",
  "Mayan",
  "Igbo",
  "Old Norse",
  "Kikuyu",
  "Swedish",
  "Medieval Low German",
  "Sinhalese",
  "Finnish Mythology",
  "Zapotec",
  "Pet",
  "Breton",
  "Urdu",
  "Persian",
  "Faroese",
  "Czech",
  "Persian Mythology",
  "Germanic Mythology",
  "Swazi",
  "Mormon",
  "Welsh Mythology",
  "Portuguese",
  "Old Church Slavic",
  "Tibetan",
  "Tausug",
  "Circassian",
  "Chechen",
  "Medieval Turkic",
  "Fula",
  "Western African",
  "Gothic",
  "Arabic",
  "Indonesian",
  "Biblical Dutch",
  "Biblical Norwegian",
  "Medieval Welsh",
  "Slavic Mythology",
  "Old Slavic",
  "Apache",
  "Hungarian",
  "Cornish",
  "Kyrgyz",
  "Basque Mythology",
  "Khmer",
  "Yoruba",
  "Yao",
  "Armenian",
  "Arthurian Cycle",
  "Judeo-Christian-Islamic Legend",
  "Various",
  "Maori",
  "Ancient Assyrian",
  "Bhutanese",
  "Marathi",
  "Maguindanao",
  "Ethiopian",
  "Biblical Swedish",
  "Swahili",
  "Kurdish",
  "Limburgish",
  "Pictish",
  "Roman Mythology",
  "Uzbek",
  "Bosnian",
  "Aymara",
  "Chamorro",
  "Ingush",
  "Comanche",
  "Scottish Gaelic",
  "Vandalic",
  "Corsican",
  "Parthian",
  "Southern African",
  "Ga",
  "Cherokee",
  "Tahitian",
  "Biblical German",
  "History",
  "Dhivehi",
  "Latvian",
  "Ojibwe",
  "Medieval French",
  "Avar",
  "Shona",
  "Irish",
  "Buddhism",
  "Shawnee",
  "Egyptian Mythology",
  "Malayalam",
  "Hawaiian",
  "Northern African",
  "Gaulish Mythology",
  "Mapuche",
  "Literature",
  "Dagestani",
  "Nuu-chah-nulth",
  "Biblical French",
  "Old Swedish",
  "Chewa",
  "Iroquois",
  "Sumerian",
  "Tajik",
  "Greek Mythology",
  "Uyghur",
  "Chinese",
  "Indian",
  "Malay",
  "Biblical",
  "Siksika",
  "Norse Mythology",
  "Medieval Breton",
  "Medieval Irish",
  "Maltese",
  "Carolingian Cycle",
  "Ndebele",
  "Galician",
  "Yiddish",
  "Polish",
  "Biblical Danish",
  "Danish",
  "Turkish",
  "Brythonic",
  "Slovene",
  "Old Coptic",
  "Eastern African",
  "Central American",
  "Old Celtic",
  "New World Mythology",
  "Ancient Egyptian",
  "Inuit",
  "Macedonian",
  "Hebrew",
  "Gujarati",
  "Finnish",
  "Basque",
  "Frisian",
  "Yoruba Mythology",
  "Asturian",
  "Fijian",
  "Amharic",
  "Romanian",
  "Sumerian Mythology",
  "Sardinian",
  "Xhosa",
  "Inca Mythology",
  "Nahuatl",
  "Irish Mythology",
  "African Mythology",
  "Hittite Mythology",
  "Old Danish",
  "Semitic Mythology",
  "Medieval Italian",
  "Biblical Spanish",
  "Picard",
  "Somali",
  "Norwegian",
  "Ottoman Turkish",
  "Samoan",
  "Nepali",
  "Guarani",
  "Phoenician",
  "Telugu",
  "Indigenous Australian",
  "Scots",
  "Burmese",
  "African American",
  "Mayan Mythology",
  "Moldovan",
  "Astronomy",
  "German",
  "Seneca",
  "Folklore",
  "Baltic Mythology",
  "Croatian",
  "Medieval Polish",
  "Near Eastern Mythology",
  "Lithuanian",
  "Akan",
  "Coptic",
  "Old Irish",
  "Tongan",
  "Medieval Slavic",
  "Ancient Roman",
  "Odia",
  "Biblical Polish",
  "Ukrainian",
  "Georgian Mythology",
  "Tatar",
  "Tamil",
  "Medieval Mongolian",
  "Celtic Mythology",
  "Biblical Portuguese",
  "Ibibio",
  "Azerbaijani",
  "Popular Culture",
  "Medieval Czech",
  "Kannada",
  "Old Germanic",
  "Esperanto",
  "Japanese",
  "Hindi",
  "Germanic",
  "Tigrinya",
  "Ancient Armenian",
  "Pintupi",
  "Manx",
  "English",
  "Mythology",
  "Late Roman",
  "Afrikaans",
  "Babylonian",
  "Lombardic",
  "Belarusian",
  "Algonquin",
  "Late Greek",
  "Mwera",
  "Medieval Portuguese",
  "Akkadian",
  "Berber",
  "Dutch",
  "Quechua",
]
